# Generated by Django 4.2.6 on 2024-01-04 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_holiday_slot_attendance_periods_leave_advisor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='periods',
        ),
        migrations.AlterUniqueTogether(
            name='timetable',
            unique_together={('class_id', 'course_id', 'day')},
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='periods_id',
        ),
    ]
